-- Adicionar colunas adicionais à tabela escolas se não existirem
ALTER TABLE escolas ADD COLUMN IF NOT EXISTS sobre_escola VARCHAR(300) NULL;
ALTER TABLE escolas ADD COLUMN IF NOT EXISTS sobre_ensino VARCHAR(300) NULL;
ALTER TABLE escolas ADD COLUMN IF NOT EXISTS sobre_estrutura VARCHAR(300) NULL;
ALTER TABLE escolas ADD COLUMN IF NOT EXISTS instagram VARCHAR(255) NULL;
ALTER TABLE escolas ADD COLUMN IF NOT EXISTS facebook VARCHAR(255) NULL;
ALTER TABLE escolas ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(20) NULL;
ALTER TABLE escolas ADD COLUMN IF NOT EXISTS telefone_contato VARCHAR(20) NULL;
ALTER TABLE escolas ADD COLUMN IF NOT EXISTS email_contato VARCHAR(100) NULL;
